#!/bin/bash
#Run bash sieve version
# if hash ./sieve-sh.sh 2>/dev/null; then
#     echo "Running Shell sieve"
#     time ./sieve-sh.sh sieve $@
#     echo " "
# else
#     echo "Error: No Shell sieve found..."
# fi
# else
echo "Skipping shell sieve as it takes too long."
