#!/bin/bash
if [ ! -d "bin" ]; then
    mkdir bin
fi

#Check for existence of clang before compiling C++ version
if hash clang++ 2>/dev/null; then
    echo "Compiling Clang++"
    clang++ -std=c++11 -Ofast sieve-cpp.cpp -o bin/sieve-cpp-clang
else
    echo "No clang++ compiler found..."
fi
#Check for existence of g++ before compiling C++ version
if hash g++ 2>/dev/null; then
    echo "Compiling g++"
    g++ -std=c++11 -Ofast sieve-cpp.cpp -o bin/sieve-cpp-gcc
else
    echo "No g++ compiler found..."
fi

#Check for existence of gcc before compiling C version
if hash gcc 2>/dev/null; then
    echo "Compiling gcc"
    gcc -std=c99 -Ofast sieve-c.c -o bin/sieve-c-gcc -lm
else
    echo "No gcc compiler found..."
fi

#Check for existence of gcc before compiling C version
if hash clang 2>/dev/null; then
    echo "Compiling clang"
    clang -std=c99 -Ofast sieve-c.c -o bin/sieve-c-clang -lm
else
    echo "No gcc compiler found..."
fi

#Check for existence of dmd before compiling
if hash dmd 2>/dev/null; then
    echo "Compiling DMD"
    dmd -O -release -inline -boundscheck=off -ofbin/sieve-dlang sieve-dlang.d
else
    echo "Error: DMD not found..."
fi

#Check for existence of rustc before compiling
if hash rustc 2>/dev/null; then
    echo "Compiling Rust"
    rustc -O sieve-rust.rs -o bin/sieve-rust
else
    echo "Error: Rust not found..."
fi

#Check for existence of Java before compiling
if hash javac 2>/dev/null; then
    echo "Compiling Java"
    javac SieveJava.java
    mv *.class ./bin/
else
    echo "Error: Java not found..."
fi

#Check for existence of Scala before compiling
if hash scalac 2>/dev/null; then
    echo "Compiling Scala"
    scalac SieveScala.scala
    mv *.class ./bin/
else
    echo "Error: Scala not found..."
fi

#Check for existence of Lua before compiling
if hash luac 2>/dev/null; then
    echo "Compiling Lua"
    luac -s -o bin/sieve-lua.luac sieve-lua.lua
else
    echo "Error: Lua not found..."
fi

echo "Done."
