#!/bin/bash
sieveSize=10000000

if [ $# -eq 0 ]
  then
    echo "No arguments supplied, using defaults."
else
  if [ -z "$1" ]
    then
      echo "No argument supplied, using defaults."
  else
    sieveSize=$1
  fi
fi

if [ ! -d "bin" ]; then
  echo "Compiled Sieves have not been compiled, run ./compile-all"
fi

set -e

#Change directories to the compiled sieves' location
if [ -d "bin" ]; then
  cd bin

  #Check for existence of clang C++ version before running
  if hash ./sieve-cpp-clang 2>/dev/null; then
      echo "Running Clang++ sieve"
      time ./sieve-cpp-clang $sieveSize
      echo ""
  else
      echo "Error: No clang++ sieve found..."
  fi

  #Check for existence of gcc C++ version before running
  if hash ./sieve-cpp-gcc 2>/dev/null; then
      echo "Running G++ sieve"
      time ./sieve-cpp-gcc $sieveSize
      echo ""
  else
      echo "Error: No g++ sieve found..."
  fi

  #Check for existence of gcc C version before running
  if hash ./sieve-c-gcc 2>/dev/null; then
      echo "Running GCC sieve"
      time ./sieve-c-gcc $sieveSize
      echo ""
  else
      echo "Error: No gcc sieve found..."
  fi

  #Check for existence of clang C version before running
  if hash ./sieve-c-clang 2>/dev/null; then
      echo "Running Clang sieve"
      time ./sieve-c-clang $sieveSize
      echo ""
  else
      echo "Error: No clang sieve found..."
  fi

  #Check for existence of dmd version before running
  if hash ./sieve-dlang 2>/dev/null; then
      echo "Running DMD sieve"
      time ./sieve-dlang $sieveSize
      echo " "
  else
      echo "Error: No D sieve found..."
  fi

  #Check for existence of Rust version before running
  if hash ./sieve-rust 2>/dev/null; then
      echo "Running Rust sieve"
      time ./sieve-rust $sieveSize
      echo " "
  else
      echo "Error: No Rust sieve found..."
  fi

  #Check for existence of Java version before running
  if hash ./SieveJava.class 2>/dev/null; then
      echo "Running Java sieve"
      time java SieveJava $sieveSize
      echo " "
  else
      echo "Error: No Java sieve found..."
  fi

  #Check for existence of C# version before running
  if hash ./SieveJava.class 2>/dev/null; then
      echo "Running C# sieve"
      time mono sieve-cs.exe $sieveSize
      echo " "
  else
      echo "Error: No C# sieve found..."
  fi

  #Check for existence of Scala version before running
  if hash ./SieveScala.class 2>/dev/null; then
      echo "Running Scala sieve"
      time scala SieveScala $sieveSize
      echo " "
  else
      echo "Error: No Scala sieve found..."
  fi


  #Check for existence of Lua and Lua sieve version
  if hash lua 2>/dev/null; then
      if hash ./sieve-lua.luac 2>/dev/null; then
          echo "Running Luac sieve"
          time lua sieve-lua.luac $sieveSize
          echo " "
      else
          echo "Error: No Luac sieve found..."
      fi
  else
      echo "Error: Luac not found..."
  fi

  #We have finished running the compiled sieves, now run the interpreted
  cd ..
fi

#Check for existence of Lua and Lua sieve version
if hash lua 2>/dev/null; then
    if hash ./sieve-lua.lua 2>/dev/null; then
        echo "Running Lua sieve"
        time lua sieve-lua.lua $sieveSize
        echo " "
    else
        echo "Error: No Lua sieve found..."
    fi
else
    echo "Error: Lua not found..."
fi

#Check for existence of Ruby and Ruby sieve version
if hash ruby 2>/dev/null; then
    if hash ./sieve_ruby.rb 2>/dev/null; then
        echo "Running Ruby sieve"
        time ruby sieve_ruby.rb $sieveSize
        echo " "
    else
        echo "Error: No Ruby sieve found..."
    fi
else
    echo "Error: Ruby not found..."
fi

#Check for existence of Pypy and Python sieve version
if hash pypy 2>/dev/null; then
    if hash ./sieve-py.py 2>/dev/null; then
        echo "Running Pypy sieve"
        time pypy sieve-py.py $sieveSize
        echo " "
    else
        echo "Error: No Pypy sieve found..."
    fi
else
  echo "Error: Pypy 3 not found..."
fi

#Check for existence of Python3 and Python sieve version
if hash python3 2>/dev/null; then
    if hash ./sieve-py.py 2>/dev/null; then
        echo "Running Python 3 sieve"
        time python3 sieve-py.py $sieveSize
        echo " "
    else
        echo "Error: No Python 3 sieve found..."
    fi
else
  echo "Error: Python 3 not found..."
fi

#Check for existence of Python 2 and Python sieve version
if hash python 2>/dev/null; then
    if hash ./sieve-py.py 2>/dev/null; then
        echo "Running Python 2 sieve"
        time python sieve-py.py $sieveSize
        echo " "
    else
        echo "Error: No Python sieve found..."
    fi
else
    echo "Error: Python 2 not found..."
fi

#Check for existence of Node and JS sieve version
if hash node 2>/dev/null; then
    if hash ./sieve-js.js 2>/dev/null; then
        echo "Running JavaScript sieve"
        time node --max-old-space-size=8192 sieve-js.js $sieveSize
        echo " "
    else
        echo "Error: No JavaScript sieve found..."
    fi
else
    echo "Error: Node not found..."
fi

#Check for existence of Perl and Perl sieve version
if hash perl 2>/dev/null; then
    if hash ./sieve-perl.pl 2>/dev/null; then
        echo "Running Perl sieve"
        time perl sieve-perl.pl $sieveSize
        echo " "
    else
        echo "Error: No Perl sieve found..."
    fi
else
    echo "Error: Perl not found..."
fi

#Run bash sieve version (takes a LONG time...)
# if hash ./sieve-sh.sh 2>/dev/null; then
#     echo "Running Shell sieve"
#     time ./sieve-sh.sh sieve $sieveSize
#     echo " "
# else
#     echo "Error: No Shell sieve found..."
# fi
# else

echo "Done."
