#!/bin/bash
if [ ! -d "bin" ]; then
    echo "\033[33mD sieve not compiled. \033[0m"
else
    cd bin
    #Check for existence of D version before running
    if hash sieve_dlang 2>/dev/null; then
        echo "\033[32mRunning D sieve \033[0m"
        time ./sieve_dlang $@
        echo " "
    else
        echo "\033[31mError: No D sieve found... \033[0m"
    fi
    cd ..
fi
