#!/bin/bash
if [ ! -d "bin" ]; then
    echo "D sieve not compiled."
else
    cd bin
    #Check for existence of D version before running
    if hash sieve_dlang 2>/dev/null; then
        echo "Running D sieve"
        time ./sieve_dlang $@
        echo " "
    else
        echo "Error: No D sieve found..."
    fi
    cd ..
fi
