#!/bin/bash
set -e

DIRS=`ls -l . | egrep '^d' | awk '{print $9}'`

# and now loop through the directories:
for DIR in $DIRS
do
  cd ${DIR}
  #Check for existence of run script before running
  if hash build 2>/dev/null; then
    sh ./build
  else
    echo "Error: No build script in directory ${DIR}"
  fi
  cd ..
done
