#!/bin/bash
sieveSize=10000000
if [ $# -eq 0 ]
  then
    echo "No arguments supplied, using defaults."
else
  if [ -z "$1" ]
    then
      echo "No argument supplied, using defaults."
  else
    sieveSize=$1
  fi
fi

set -e

DIRS=`ls -l . | egrep '^d' | awk '{print $9}'`

# and now loop through the directories:
for DIR in $DIRS
do
  cd ${DIR}
  #Check for existence of run script before running
  if hash run 2>/dev/null; then
    sh ./run $sieveSize
  else
    echo "Error: No run script in directory ${DIR}"
  fi
  cd ..
done
