#!/bin/bash
#Check for existence of Node and JS sieve version
if hash node 2>/dev/null; then
    if hash ./sieve_javascript.js 2>/dev/null; then
        echo "\033[32mRunning JavaScript sieve\033[0m"
        time node --max-old-space-size=8192 sieve_javascript.js $@
        echo " "
    else
        echo "\033[31mError: No JavaScript sieve found...\033[0m"
    fi
else
    echo "\033[31mError: Node not found...\033[0m"
fi
