#!/bin/bash
if [ ! -d "bin" ]; then
    mkdir bin
fi

#Check for existence of MCS before compiling
if hash mcs 2>/dev/null; then
    echo "\033[32mCompiling C#\033[0m"
    mcs sieve_csharp.cs -out:bin/sieve_csharp.exe
else
    echo "\033[31mError: MCS not found...\033[0m"
fi
