#!/bin/bash
if [ ! -d "bin" ]; then
    echo "\033[33mC# sieve not compiled.\033[0m"
else
    cd bin
    #Check for existence of C# version before running
    if hash sieve_csharp.exe 2>/dev/null; then
        echo "\033[32mRunning C# sieve\033[0m"
        time mono sieve_csharp.exe $@
        echo " "
    else
        echo "\033[31mError: No C# sieve found...\033[0m"
    fi
    cd ..
fi
