#!/bin/bash
#Check for existence of Perl and Perl sieve version
if hash perl 2>/dev/null; then
    if hash ./sieve_perl.pl 2>/dev/null; then
        echo "\033[32mRunning Perl sieve\033[0m"
        time perl sieve_perl.pl $@
        echo " "
    else
        echo "\033[31mError: No Perl sieve found...\033[0m"
    fi
else
    echo "\033[31mError: Perl not found...\033[0m"
fi
