#!/bin/bash
if [ ! -d "bin" ]; then
    mkdir bin
fi

#Check for existence of Lua before compiling
if hash luac 2>/dev/null; then
    echo "\033[32mCompiling Lua\033[0m"
    luac -s -o bin/sieve_lua.luac sieve_lua.lua
else
    echo "\033[31mError: Lua not found...\033[0m"
fi
