build: 

run: sieve_python.py
	@echo "Running python2 sieve"
	python2 sieve_python.py ${SIEVESIZE}

	@echo "Running python3 sieve"
	python3 sieve_python.py ${SIEVESIZE}

	@echo "Running pypy sieve"
	pypy sieve_python.py ${SIEVESIZE}

clean:

.PHONY: run 