#!/bin/bash
if [ ! -d "bin" ]; then
    mkdir bin
fi

#Check for existence of Java before compiling
if hash javac 2>/dev/null; then
    echo "\033[32mCompiling Java\033[0m"
    javac SieveJava.java
    mv *.class ./bin/
else
    echo "\033[31mError: Java not found...\033[0m"
fi
