#!/bin/bash
if [ ! -d "bin" ]; then
    echo "\033[33mJava sieve not compiled.\033[0m"
else
    cd bin
    #Check for existence of Java version before running
    if hash ./SieveJava.class 2>/dev/null; then
        echo "\033[32mRunning Java sieve\033[0m"
        time java SieveJava $@
        echo " "
    else
        echo "\033[31mError: No Java sieve found...\033[0m"
    fi
    cd ..
fi
