#!/bin/bash
#Check for existence of Ruby and Ruby sieve version
if hash ruby 2>/dev/null; then
    if hash ./sieve_ruby.rb 2>/dev/null; then
        echo "\033[32mRunning Ruby sieve\033[0m"
        time ruby sieve_ruby.rb $@
        echo " "
    else
        echo "\033[31mError: No Ruby sieve found...\033[0m"
    fi
else
    echo "\033[31mError: Ruby not found...\033[0m"
fi
