#!/bin/bash
if [ ! -d "target" ]; then
    echo "\033[33mRust sieve not compiled.\033[0m"
else
    cd target
    if [ ! -d "release" ]; then
        echo "\033[33mRust sieve not compiled.\033[0m"
    else
        cd release
        #Check for existence of compiled Rust version before running
        if hash sieve_rust 2>/dev/null; then
            echo "\033[32mRunning Rust sieve\033[0m"
            time ./sieve_rust $@
            echo " "
        else
            echo "\033[31mError: No Rust sieve found...\033[0m"
        fi
        cd ..
    fi
    cd ..
fi
