#!/bin/bash
if [ ! -d "bin" ]; then
    echo "\033[33mScala sieve not compiled.\033[0m"
else
    cd bin
    #Check for existence of Scala version before running
    if hash ./SieveScala.class 2>/dev/null; then
        echo "\033[32mRunning Scala sieve\033[0m"
        time scala SieveScala $@
        echo " "
    else
        echo "\033[31mError: No Scala sieve found...\033[0m"
    fi
    cd ..
fi
