#!/bin/bash
if [ ! -d "bin" ]; then
    mkdir bin
fi

#Check for existence of gcc before compiling C version
if hash gcc 2>/dev/null; then
    echo "\033[32mCompiling gcc\033[0m"
    gcc -std=c99 -Ofast sieve_c.c -o bin/sieve_c_gcc -lm
else
    echo "\033[31mNo gcc compiler found...\033[0m"
fi

#Check for existence of clang before compiling C version
if hash clang 2>/dev/null; then
    echo "\033[32mCompiling clang\033[0m"
    clang -std=c99 -Ofast sieve_c.c -o bin/sieve_c_clang -lm
else
    echo "\033[31mNo clang compiler found...\033[0m"
fi
