#!/bin/bash
if [ ! -d "bin" ]; then
    mkdir bin
fi

#Check for existence of clang before compiling C++ version
if hash clang++ 2>/dev/null; then
    echo "\033[32mCompiling Clang++\033[0m"
    clang++ -std=c++11 -Ofast sieve_cpp.cpp -o bin/sieve_cpp_clang
else
    echo "\033[31mNo clang++ compiler found...\033[0m"
fi
#Check for existence of g++ before compiling C++ version
if hash g++ 2>/dev/null; then
    echo "\033[32mCompiling g++\033[0m"
    g++ -std=c++11 -Ofast sieve_cpp.cpp -o bin/sieve_cpp_gcc
else
    echo "\033[31mNo g++ compiler found...\033[0m"
fi
